### ISSUE TITLE
Button component onClick event working even after disabling

### ISSUE THREAD

**Issue by tsukhu** [hackclub/design-system#6]
When using the Button component with disable set at true , while the button is greyed out , but it still causes the onClick event to be fired 
For example:
```
<Button onClick={this.handleClose} scale={true} disabled={true}>
              SAVE
</Button>
```

**Comment by merelinguist** [comment]
The problem isn't with disabled; it's with the HTML element `a`. Anchor `<a>` tags cannot have a disabled property (what does that even mean?). Just because you've passed CSS to make the element look like a button, doesn't make it a button. It is still an anchor. 

You could handle this in handleClose:

```jsx
handleClose () {
  if (!this.state.readyToView) return
  // ...
}
```

**Comment by lachlanjc** [comment]
Yep, @merelinguist is correct. You can also add `cursor: disabled;` and `pointer-events: none;` in the CSS.

**Comment by tsukhu** [comment]
Fair enough.. I will try to extend Button component to    add this functionality..
